version: '3.4'

services:
  microservice:
    image: ${DOCKER_REGISTRY-}microservice
    build:
      context: .
      dockerfile: Microservice/Dockerfile

  microservice002:
    image: ${DOCKER_REGISTRY-}microservice002
    build:
      context: .
      dockerfile: MicroService002/Dockerfile

