version: '3.4'

services:
  microservice.begonia:
    image: ${DOCKER_REGISTRY-}microservicebegonia
    build:
      context: .
      dockerfile: MicroService.Begonia/Dockerfile

  microservice.thirdparty:
    image: ${DOCKER_REGISTRY-}microservicethirdparty
    build:
      context: .
      dockerfile: Microservice.ThirdParty/Dockerfile

